kind: PersistentVolume
apiVersion: v1
metadata:
  name: prod-repositories
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: "prod-repositories"
    fsType: "ext4"
