#!/bin/zsh
pod_name() { kubectl get pods -o jsonpath="{@.items[*].metadata.name}"|grep -E "$1-[^ ]*" -o; }
delete_pod() { kubectl delete pod/$(pod_name $1); }
logs() {
    kubectl get pods | grep $1;
    kubectl attach $(pod_name $1); 
}
describe_pod() { kubectl describe pod/$(pod_name $1); }
shell_pod() { kubectl exec -it $(pod_name $1) bash; }
attach_pod() { kubectl attach $(pod_name $1); }
sidecar() { kubectl logs $(pod_name mongo-$1-$2) -c mongo-sidecar; }

alias pods='kubectl get pods'
alias rcs='kubectl get rcs'
alias svcs='kubectl get svc'

