version: '2'
services:
  mongorocks:
    container_name: mongorocks
    build:
      context: ./mongorocks
    volumes:
     - ./db:/db
     - ./backups:/backups
    image: mongorocks
    network_mode: "host"
    entrypoint: mongod --dbpath /db --storageEngine=rocksdb
  pyrocksdb:
    container_name: pyrocksdb
    build:
      context: ./pyrocksdb
    volumes:
      - ./db:/db
      - ./pyrocksdb_backups:/pyrocksdb_backups
    image: pyrocksdb
  strata:
    container_name: strata
    build:
      context: ./strata
    volumes:
      - ./db:/db
    image: strata
  pymongo:
    container_name: pymongo
    build:
      context: ./pymongo
    volumes:
      - ./db:/db
    image: pymongo
