version: '2'
services:
  waverbase-www:
    build:
      context: ../
      dockerfile: ./waverbase-www/ops/Dockerfile
    volumes:
      - ../waverbase-www/src:/home/waverbase/waverbase/waverbase-www/src
    ports:
      - "8080:8080"
  # waverbase-thrift-api:
  #   build:
  #     context: ../
  #     dockerfile: ./waverbase-thrift-api/ops/Dockerfile
  #   volumes:
  #     - ../waverbase-thrift-api/src:/home/waverbase/waverbase/waverbase-thrift-api/src
  #   ports:
  #     - "9090:9090"
