version: '2'
services:
  waverbase-www:
    build:
      context: ../
      dockerfile: ./waverbase-www/ops/Dockerfile
    volumes:
      - ../waverbase-www/src:/home/waverbase/waverbase/waverbase-www/src
      - ../waverbase-thrift-api/waverbase.thrift:/home/waverbase/waverbase/waverbase-thrift-api/waverbase.thrift
    ports:
      - "8080:8080"
    depends_on:
      - waverbase-thrift-api
  waverbase-thrift-api:
    build:
      context: ../
      dockerfile: ./waverbase-thrift-api/ops/Dockerfile
    volumes:
      - ../waverbase-thrift-api/src:/home/waverbase/waverbase/waverbase-thrift-api/src
      - ../waverbase-thrift-api/waverbase.thrift:/home/waverbase/waverbase/waverbase-thrift-api/waverbase.thrift
    ports:
      - "9099:9099"
    depends_on:
      - mongo-dev
      - email-sender
  email-sender:
    build:
      context: ../
      dockerfile: ./email-sender/ops/Dockerfile
    volumes:
      - ../email-sender/src:/home/waverbase/waverbase/email-sender/src
      - ../email-sender/email-sender.thrift:/home/waverbase/waverbase/email-sender/email-sender.thrift
  mongo-dev:
    image: mongo
