version: '2'
services:
  website-service:
    build:
      context: ../
      dockerfile: ./website-service/ops/Dockerfile
    container_name: 'website-service'
    volumes:
      - ../website-service/images:/home/waverbase/waverbase/website-service/images
      - ../website-service/semantic:/home/waverbase/waverbase/website-service/semantic
      - ../website-service/src:/home/waverbase/waverbase/website-service/src
      - ../website-service/thrift.js:/home/waverbase/waverbase/website-service/thrift.js
      - ../website-service/webpack.config.js:/home/waverbase/waverbase/website-service/webpack.config.js
      - ../public-api-service/public-api.thrift:/home/waverbase/waverbase/public-api-service/public-api.thrift
    ports:
      - "8080:8080"
    depends_on:
      - public-api-service
  public-api-service:
    build:
      context: ../
      dockerfile: ./public-api-service/ops/Dockerfile
    volumes:
      - ../public-api-service/ops:/home/waverbase/waverbase/public-api-service/ops
      - ../public-api-service/src:/home/waverbase/waverbase/public-api-service/src
      - ../public-api-service/public-api.thrift:/home/waverbase/waverbase/public-api-service/public-api.thrift
      - ../public-api-service/webpack.config.js:/home/waverbase/waverbase/public-api-service/webpack.config.js
    ports:
      - "9099:9099"
    depends_on:
      - mongo-dev
      - email-sender-service
  email-sender-service:
    build:
      context: ../
      dockerfile: ./email-sender-service/ops/Dockerfile
    volumes:
      - ../email-sender-service/ops:/home/waverbase/waverbase/email-sender-service/ops
      - ../email-sender-service/src:/home/waverbase/waverbase/email-sender-service/src
      - ../email-sender-service/email-sender.thrift:/home/waverbase/waverbase/email-sender-service/email-sender.thrift
  mongo-dev:
    image: mongo
