kind: ReplicationController
apiVersion: v1
metadata:
  name: app-service
spec:
  replicas: 1
  selector:
    name: app-service
  template:
    spec:
      containers:
        - name: app-service
          image: eu.gcr.io/api-project-1075799951054/app-service:latest
          limits:
            cpu: 500m
            memory: 200Mi
          ports:
            - containerPort: 9090
    metadata:
      labels:
        name: app-service
