apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  ports:
    - port: 5671
      name: dist
    - port: 5672
      name: node

  selector:
    name: rabbitmq
