kind: ReplicationController
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    name: rabbitmq
  template:
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          ports:
            - containerPort: 5671
            - containerPort: 5672
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: RABBITMQ_BASE
              value: /data
              
          volumeMounts:
            - name: rabbitmq-persistent-storage
              mountPath: /data
      volumes:
        - name: rabbitmq-persistent-storage
          gcePersistentDisk:
            pdName: rabbitmq-waver
            fsType: ext4
    metadata:
      labels:
        name: rabbitmq
